<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");

/** @global object $APPLICATION */
$sectionId = "";
if(isset($_GET['type'])) {
	$APPLICATION->SetTitle("Подать объявление");
	$sectionId = $_GET['type'];
	$template = 'fields';
} else {
	$APPLICATION->SetTitle("Выберите категорию");
	$template = 'sections';
}
?>
<?$APPLICATION->IncludeComponent(
	"web:create.element",
	$template,
	array(
		"IS_TEMPLATE_INCLUDE" => "Y",
		"COMPONENT_TEMPLATE" => ".default",
		"IBLOCK_TYPE" => "aspro_max_catalog",
		"IBLOCK_ID" => "26",
		"SECTION_ID" => $sectionId,
		"AUTH_LINK" => '/auth',
		"SUCCESS_LINK" => '/personal',
		"LIST_PROPERTIES" => array(
			0 => "ID",
			1 => "IBLOCK_ID",
			2 => "SECTIONS",
			3 => "NAME",
			4 => "PREVIEW_PICTURE",
			5 => "DETAIL_PICTURE",
			6 => "",
		),
		"LIST_FIELDS" => array(
			0 => "complect_atv",
			1 => "complect_scooter",
			2 => "complect_snow",
			3 => "MINIMUM_PRICE",
			4 => "MAXIMUM_PRICE",
			5 => "MARKA",
			6 => "MODEL",
			7 => "CITY",
			8 => "city_other",
			9 => "capacity_motor",
			10 => "type_atv",
			11 => "type_bike",
			12 => "type_scooter",
			13 => "type_snow",
			14 => "state",
			15 => "cylinders_count_atv",
			16 => "cylinders_count_bike",
			17 => "complect_bike",
			18 => "cylinders_count_scooter",
			19 => "cylinders_count_snow",
			20 => "HIT",
			21 => "color",
			22 => "signalling",
			23 => "xenon_lights",
			24 => "immobilizer",
			25 => "other_transmission",
			26 => "full_drive",
			27 => "sensor_parking",
			28 => "invalid",
			29 => "window_raiser",
			30 => "hydraulic_booster",
			31 => "leather_salon",
			32 => "engine_room_hatch",
			33 => "warm_seat",
			34 => "mobile",
			35 => "ABS",
			36 => "steadiness",
			37 => "thermo_control",
			38 => "navigation_system",
			39 => "central_lock",
			40 => "pillow_safety",
			41 => "componentry_tuning",
			42 => "webasto",
			43 => "cast_disk",
			44 => "year",
			45 => "race",
			46 => "race_unit",
			47 => "MODEL_OTHER",
			48 => "PROP_375",
			49 => "PROP_373",
			50 => "PROP_374",
			51 => "power",
			52 => "PROP_371",
			53 => "motor_type_atv",
			54 => "motor_type_bike",
			55 => "motor_type_scooter",
			56 => "motor_type_snow",
			57 => "count_door_atv",
			58 => "count_door_bike",
			59 => "count_door_scooter",
			60 => "count_door_snow",
			61 => "auction",
			62 => "contact_person",
			63 => "email",
			64 => "phone",
			65 => "VIDEO_YOUTUBE",
			66 => "height",
			67 => "length",
			68 => "coordinations",
			69 => "square",
			70 => "width",
			71 => "high",
			72 => "transmission",
			73 => "model_MARKA",
			74 => "model_MODEL",
			75 => "basket",
			76 => "cat_modify",
			77 => "modify",
			78 => "",
		)
	),
	false
);?>
<?php require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>